name: ProFlow
description: An app to help you better manage your PW

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xpath_selector: ^3.0.2
  flutter_iconpicker: ^3.2.4
  http: ^0.13.0
  cupertino_icons: ^1.0.2
  gsheets: ^0.3.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_svg: ^1.1.6
  cloud_firestore: ^4.8.1
  google_sign_in: ^5.4.4
  shared_preferences: ^2.2.0
  get: ^4.6.5
  get_storage: ^2.1.1
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.0.0+3
  step_progress_indicator: ^1.0.2
  intl: ^0.17.0
  flutter_launcher_icons: ^0.11.0
  video_player: ^2.6.1
  google_fonts: ^4.0.4
  image: ^3.3.0
  flutter_chat_ui: ^1.6.6
  grouped_list: ^5.1.2
  chat_bubbles: ^1.4.0
  onboarding: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: "2.2.16"
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icon.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/ProFlow(2).png
    - assets/proflow.svg
    - assets/note.png
    - assets/mdhash.js
    - assets/splash_video.mp4
    - assets/list.png
    - assets/logout.png
    - assets/text-voice-channel.png
    - assets/vector.png
    - assets/logo.png
    - assets/search.png
    - assets/logo-ZUa.png
    - assets/tasklist.png
    - assets/forum.png
